; NESBRETTE ADDRESS LISTING
; MODIFYING THESE WILL CHANGE WHERE NESBRETTE ROUTINES TARGET

; FUNCTION_DIVIDE
.define FUNCTION_DIVIDE_NUMERATOR   $07 ; ZP 1 byte
.define FUNCTION_DIVIDE_DENOMINATOR $08 ; ZP 1 byte
.if DIVIDE_FAST_POWER_OF_TWO = 0
    FUNCTION_DIVIDE_TEMP            = $0d
.endif

; FUNCTION_ROOT
.define FUNCTION_ROOT_ROOT          $02 ; ZP 1 byte
.define FUNCTION_ROOT_REM           $03 ; ZP 1 byte
.define FUNCTION_ROOT_IN_HIGH       $00 ; ZP 1 byte
.define FUNCTION_ROOT_IN_LOW        $01 ; ZP 1 byte

; FUNCTION_HYPOTENUSES
.define FUNCTION_HYPOTENUSE_A       $06 ; ZP 1 byte
.define FUNCTION_HYPOTENUSE_O       FUNCTION_HYPOTENUSE_A + 1 ; ZP 1 byte

; RAYCAST_CALCULATE
.define RAYCAST_A_COARSE            $09
.define RAYCAST_A_FINE              $0a
.define RAYCAST_O_COARSE            $0b
.define RAYCAST_O_FINE              $0c
.define RAYCAST_INTERVAL_ADDR       $0e
.define RAYCAST_TEMP                $0f