; NESBRETTE ADDRESS LISTING
; MODIFYING THESE WILL CHANGE WHERE NESBRETTE ROUTINES TARGET

; FUNCTION_DIVIDE
.define FUNCTION_DIVIDE_NUMERATOR   $00 ; ZP 1 byte
.define FUNCTION_DIVIDE_DENOMINATOR $01 ; ZP 1 byte