; NESBRETTE CONSTANT LISTING
; THESE VALUES WILL DETERMINE WHAT FEATURES CAN BE USED AND HOW THEY WILL BE USED

.define MAPPER                      0


; RAYCASTING
.define RAYCAST_FIXED_INTERVAL      8