ADDRESSES_MATH_ADD_OUT      = $300
ADDRESSES_MATH_ADD_MOD      = $304
ADDRESSES_MATH_ADD_WIDTH    = $00

ADDRESSES_MATH_SUB_OUT      = ADDRESSES_MATH_ADD_OUT
ADDRESSES_MATH_SUB_MOD      = ADDRESSES_MATH_ADD_MOD
ADDRESSES_MATH_SUB_WIDTH    = ADDRESSES_MATH_ADD_WIDTH