; math cmult

ADDRESSES_MATH_ADD_MOD      = $300
ADDRESSES_MATH_ADD_MOD      = $300 + CONSTANTS_MATH_ADD_WIDTH
ADDRESSES_MATH_SUB_MOD      = $300
ADDRESSES_MATH_SUB_MOD      = $300 + CONSTANTS_MATH_SUB_WIDTH
CONSTANTS_MATH_ADD_WIDTH    = 4
CONSTANTS_MATH_SUB_WIDTH    = CONSTANTS_MATH_ADD_WIDTH

CONSTANTS_MATH_CMULT_TEMP   = $300 + CONSTANTS_MATH_ADD_WIDTH