INCLUDES_NESBRETTE_HEADER                   = 1

INCLUDES_NESBRETTE_MATH_ADD                 = 1
INCLUDES_NESBRETTE_MATH_SUB                 = 1
INCLUDES_NESBRETTE_MATH_CMULT               = 1

INCLUDES_NESBRETTE_MATH_TRIG_SIN            = 0
INCLUDES_NESBRETTE_MATH_TRIG_COS            = 0

INCLUDES_NESBRETTE_IDTABLE_INSTRUCTIONS     = 0
INCLUDES_NESBRETTE_IDTABLE_ILLEGAL          = 0